### ISSUE TITLE
Problem with the '.ini'  importer

### ISSUE THREAD

**Issue by boltex** [boltex/leojs#94]
From @tbpassin : 

All right, it installed in vsc and it did open an outline.  I saw a lot of errors like this:

reading settings in C:/Users/tom/.leo/workbook.leo
TypeError: Cannot read properties of undefined (reading 'trim')
	at Ini_Importer.find_blocks (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:1507413)
	at Ini_Importer.gen_block (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:1508153)
	at Ini_Importer.gen_lines (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:1511889)
	at Ini_Importer.import_from_string (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:1512400)
	at exports.do_import (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:1522910)
	at LeoImportCommands.createOutline (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:1338218)
	at async AtFile.readOneAtAutoNode (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:955878)
	at async AtFile.readFileAtPosition (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:954544)
	at async AtFile.readAll (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:953359)
	at async FileCommands.readExternalFiles (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:1151896)
	at async FileCommands._getLeoFileByName (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:1151493)
	at async FileCommands.getAnyLeoFileByName (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:1149953)
	at async LoadManager.openFileByName (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:937514)
	at async LoadManager.loadLocalFile (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:936309)
	at async SessionManager.load_session (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:1439599)
	at async LoadManager.doPostPluginsInit (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:932259)
	at async LoadManager.load (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:931126)
	at async runLeo (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:1807739)
	at async activate (c:\Users\tom\.vscode\extensions\boltex.leojs-0.2.0\dist\extension-node.js:2:1815070)
	at async u.n (c:\Users\tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:6255)
	at async u.m (c:\Users\tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:6218)
	at async u.l (c:\Users\tom\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:140:5675)

**Comment by boltex** [comment]
@tbpassin Can you provide me with the .ini file that your leo file is trying to refresh at startup?

**Comment by boltex** [comment]
I think this is related to Leo's issue: https://github.com/leo-editor/leo-editor/issues/3727  😄

**Comment by boltex** [comment]
@tbpassin Oh i had a mistranlation in the ini importer's regex. Will be fixed in next release tomorrow.

**Comment by tbpassin** [comment]
Here are the two external .ini files I have in the workbook. The errors must have come during processing them.

[inifiles.zip](https://github.com/boltex/leojs/files/13759373/inifiles.zip)

**Comment by boltex** [comment]
@tbpassin  I would have needed the ini files themselves zipped, not the leo file  alone that you zipped, for which the inner @auto and @clean nodes have nothing to pikup upon... and therefore endup almost empty 😢

**Comment by tbpassin** [comment]
Oops, sorry.  I forgot that.  Coming right up.

[inifiles.zip](https://github.com/boltex/leojs/files/13760397/inifiles.zip)

**Comment by boltex** [comment]
@tbpassin That did the trick! 👍  Today's new release has gotten rid of those errors! 

Thanks for testing out and reporting what you find! Really very much appreciated!!

With your help, we'll get rid of the remaining bugs and get to a full LeoJS 1.0 release much more quickly! Thanks again Thomas!!

**Comment by tbpassin** [comment]
: )

**Comment by tbpassin** [comment]
I didn't get any error messages on opening leoJS with the new release.

```
LeoJS 0.2.7, master branch, build 1ae8764
2023-12-23 20:17:31 -0500
Node.js v18.15.0, VSCode version 1.85.1
```
